name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main # Развертывать при коммите в ветку 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Worker using Cloudflare Action
        uses: cloudflare/wrangler-action@v3
        with:
          quiet: false 
          command: deploy --name gemini-photo-bot worker.js --verbose 
        # Блок env должен быть на том же уровне отступа, что и uses: и with:
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
